# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
version: "1"
rules:
  - base: main
    upstream: open-telemetry:main
    mergeMethod: rebase
    conflictReviewers:
      - apeirora/audit-logger
  - base: upstream
    upstream: open-telemetry:main
    mergeMethod: hardreset
    mergeUnstable: true
